[project]
name = "create-pid"
version = "0.1.0"
description = "Kode for Ã¥ lage PID til ressurser til ressurskatalogen"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
